### ISSUE TITLE
Training on different sizes of graphs

### ISSUE THREAD

**Issue by BabyCodr** [tomdbar/eco-dqn#1]
The current implementation trains using sets of graphs with constant size. How difficult would it be to generalise the training to train on graphs of various sizes (say in a range according to uniform distribution)?

**Comment by tomdbar** [comment]
Conceptually, this is straightforward - there is no reason all training graphs have to be the same size (though if graphs have significantly different numbers of vertices, the lengths of the episodes might need to be correspondingly adjusted too).

Practically it would be a little more involved but certainly possible.  The best way to do this would be to stop representing graphs with an adjacency matrix and start representing them as a list of nodes and edges (which would mostly just require a reworking of the message-passing network to this formalism).  I've moved towards this in other un-published works but a good place to look might be DeepMinds [Graph Net's](https://github.com/deepmind/graph_nets) library where they take this approach (though this is in TensorFlow).

I'm closing this issue for now though, as I won't be making this change to eco-dqn as it's publication code and so needs to stay representative of what was used for the paper.

**Comment by AnantMaheshwari** [comment]
Hey! I was curious in case this has been implemented or explored further since this issue was closed (either within this project or for another project), wanted to experiment with this implementation for training on a distribution of graphs of different sizes and was wondering if this has already been implemented! Thanks so much.
