### ISSUE TITLE
Difference between testing during training and testing after training

### ISSUE THREAD

**Issue by BabyCodr** [tomdbar/eco-dqn#2]
Looking at the implementation I see that testing during training to produce the learning curve is implemented in a different way compared to testing after training. Are there any technical differences between the two implementations?

**Comment by tomdbar** [comment]
There is not a technical difference with regards to how the agent acts, however, there are differences between the graphs tested upon and how we evaluate each episode.

[During training](https://github.com/tomdbar/eco-dqn/blob/c246957d6df109991aa30af97db816c032252cfc/src/agents/dqn/dqn.py#L511), (by default) the agent will be tested on randomly generated graphs from the same distribution (i.e. the same graph generator) on which it is training (the "score" associated with each test episode is controlled by the TestMetric enum).

However, [after training](https://github.com/tomdbar/eco-dqn/blob/c246957d6df109991aa30af97db816c032252cfc/experiments/utils.py#L21) me may (and in the scripts provided, do) target a specific pre-chosen set of test graphs.  Moreover, we may use multiple episodes on each of these graphs.  Overall, we store and return much more data from these tests (such as the initial spin configuration of each episode,  the actions taken and rewards obtained at each step etc).
