### ISSUE TITLE
About computing optimality

### ISSUE THREAD

**Issue by bywbilly** [tomdbar/eco-dqn#3]
Hi, Thanks for sharing this awesome code. I am wondering how can I compute the optimality reported in the paper.

I guess I should read the graph info pickle file to get the optimality answer and compute w.r.t to them?

It would be really helpful if you could share the related code.

Thanks!

**Comment by tomdbar** [comment]
Hi,

In short, yes, the 'optimum' solution for every graph (i.e. the best result any methods, including ECO-DQN and all baselines, as detailed in the supplementary material of the paper) are provided in the ```graphs/*/opts/``` folder(s) and the approximation ratios reported in the paper are calculated with respect to these values.

Loading them is quite simple.  Here is an example script to load the list of optimum values for all 100 instances in the validation set for 100 vertex BA graphs.

```
import pickle

sols_pth = "_graphs/validation/opts/cuts_BA_100spin_m4_100graphs.pkl"
with open(sol_pth, 'rb') as f:
    sols = pickle.load(f)

print(sols)
```

**Comment by bywbilly** [comment]
@tomdbar Thanks for your reply. I tried to compute the optimality, but I found it is hard to reproduce the paper results. 
For the test function, here is the parameters I used:
![image](https://user-images.githubusercontent.com/10766902/103310854-839a8f80-49cd-11eb-8f50-2b5313f50f2b.png)
And for computing optimality:
![image](https://user-images.githubusercontent.com/10766902/103310890-9ca34080-49cd-11eb-8172-7f44606d31ee.png)
It would be really helpful if you could help me reproduce the results.

Thanks!
