### ISSUE TITLE
Question about observations invented in your paper

### ISSUE THREAD

**Issue by tztgogo** [tomdbar/eco-dqn#4]
So, according to your paper, you invented 7 observations:
1. Vertex state, i.e. if v is currently in the solution set, S.
2. Immediate cut change if vertex state is changed.
3. Steps since the vertex state was last changed.
4. Difference of current cut-value from the best observed.
5. Distance of current solution set from the best observed.
6. Number of available actions that immediately increase the cut-value.
7. Steps remaining in the episode.

And you said that (4-6) ensures the extrinsic and intrinsic rewards are Markovian, however I do not get the point.
Could you explain it ?
Thx!

**Comment by tomdbar** [comment]
For an agent to correctly predict the rewards it will receive (and so, predict Q-values), it is required that all the information necessary to perform this calculation is contained within it's observation (this is what we mean by Markovian rewards). The reward returned at each step is the increase in cut-value beyond the best observed cut seen thus far in an episode + a small reward for the first time reaching a new local minima.  Therefore, the agent needs to know either the best cut found so far, or how far away from this the current cut value it (observation 4).  For the intrinsic rewards, it needs to know if it has visited a local minima before (which is approximated by observation 5 and found to be sufficient), and whether it is in a local minima (observation 6).

**Comment by tztgogo** [comment]
thank you for your answer！
it really helps me！





------------------ Original ------------------
From: Tom Barrett ***@***.***&gt;
Date: Sat,Apr 10,2021 7:45 PM
To: tomdbar/eco-dqn ***@***.***&gt;
Cc: Zhentao Tan ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [tomdbar/eco-dqn] Question about observations invented in your paper (#4)





 
For an agent to correctly predict the rewards it will receive (and so, predict Q-values), it is required that all the information necessary to perform this calculation is contained within it's observation (this is what we mean by Markovian rewards). The reward returned at each step is the increase in cut-value beyond the best observed cut seen thus far in an episode + a small reward for the first time reaching a new local minima.  Therefore, the agent needs to know either the best cut found so far, or how far away from this the current cut value it (observation 4).  For the intrinsic rewards, it needs to know if it has visited a local minima before (which is approximated by observation 5 and found to be sufficient), and whether it is in a local minima (observation 6).
