### ISSUE TITLE
Add Observations

### ISSUE THREAD

**Issue by rainingapple** [tomdbar/eco-dqn#7]
Hi , tomdbar . 

If I want to Add some observations , which part of your code shell I change.

**Comment by tomdbar** [comment]
Hi @rainingapple,

As this is publication code, it was not designed to allow observations to be added/removed/modified by editing only one part of the code.  However, if you do want to go this route, observations are handled in the `step` function of `spinsystem.py`, where you can see how they are calculated and added to the state (but I expect additional changes will have to be made in other parts of the code to be compatible with adding observations in the step function).

Sorry that is not more helpful!

**Comment by rainingapple** [comment]
Thanks !
